version: "3.8"

services:
  mongodb:
    image: mongo:4.2.3-bionic
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: test
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

    volumes:
      # named volumes
      - ./mongo/data:/data/db

  front-end:
    ports:
      - 80:80
    environment:
      BACKEND_URL: "http://back-end:6677/"
    build:
      context: .
      dockerfile: ./packages/front-end/dockerfile

  back-end:
    environment:
      PORT: 6677
      MONGO_URL: "mongodb://admin:admin@mongodb:27017/"
      UNSLASH_ACCESS_KEY: "6shqDo4NVu85fDCejx1lMNaA3p1eHGe6trXqFN2smho"
      DEBUG: "mongo-seeding"
    depends_on:
      - mongodb
    ports:
      - 6677:6677
    image: back-end-prod
    build:
      context: .
      dockerfile: ./packages/back-end/dockerfile
