version: "3.8"

services:
  app:
    container_name: app-prod
    ports:
      - 80:80
    image: app-prod
    build:
      context: .
      dockerfile: ./packages/front-end/dockerfile
      target: production
